### ISSUE TITLE
Autoplay possible excessive eeprom writes

### ISSUE THREAD

**Issue by dmacias72** [evilgeniuslabs/tree-v2#13]
Setting a low autoplay interval could exceed the 100,000 write limit of the eeprom. If run 24/7 a 20 sec interval would take 23 days. 1 min interval would be 69 days.

I just added this to the adjustPattern and set Pattern functions.

if (autoplay == 0){
    EEPROM.write(1, currentPatternIndex);
    EEPROM.commit();
  }

**Comment by jasoncoon** [comment]
Cool, good catch.  Mind submitting a pull request?  Thanks!

**Comment by jasoncoon** [comment]
Resolved with pull request https://github.com/evilgeniuslabs/tree-v2/pull/15
