### ISSUE TITLE
Eliminate Mapped LEDs

### ISSUE THREAD

**Issue by terrag42** [evilgeniuslabs/tree-v2#2]
The tree video looks great! I would like to use this with my project, but I have a different number of LEDs. I would like to use your websockets app to control my LEDs. I have commented out all the patterns that use mapped LEDs. I'm getting a compiler error.
Pride2 and colorwaves2 uses "levelCount" variable.
The compiler gives the error:
'levelCount' was not declared in this scope
I believe two variables are not declared, "levelCount" and an an array, which I believe is the size of NUM_LEDS, called "levels"
What type of variables are needed, and where should I declare it (global or within the function?)
Thank you,
-Terrag42
P.S. I searched Mark Kriegsman's github gists, but did not find pride2 or colorwaves2.

**Comment by terrag42** [comment]
I was able to get it to compile by declaring two new global variables:
uint16_t levelCount;
uint8_t levels[NUM_LEDS];

**Comment by jasoncoon** [comment]
Yeah, if you're not using any of the mapping, you can just remove the Pride2 and ColorWaves2 patterns.
