### ISSUE TITLE
179 LED

### ISSUE THREAD

**Issue by viktor6** [evilgeniuslabs/tree-v2#30]
The guys who can remake for 179 LED will be very grateful, I do not have enough knowledge for this.
I don’t know where to turn anymore, I beg you.

**Comment by mariusmotea** [comment]
Is easy to made it for any number of leds if is a strip with the python script from the repo.

**Comment by viktor6** [comment]
I don’t understand how to do it. :(

**Comment by jasoncoon** [comment]
Change the numbers at the top of this file to match your needs:

https://github.com/evilgeniuslabs/tree-v2/blob/master/generate_map_h.py

Then google how to run python scripts. :)

**Comment by viktor6** [comment]
Give an example of how to run it.
